In [4]:
import numpy as np

In [309]:
exp_we = np.array([0.2, 0.5, 0.3])
ret_e = np.array([0.0, 0.04, -0.04])

ben_we = np.array([0.2, 0.2, 0.6])
ret_b = np.array([0.1, 0.04, -0.04])

n_stocks = 1
n_sectors = 3

In [ ]:
def analyzer_time_t(ret:list,  we:list, wb:list):
    """
    one-liner

    Args

    Returns
    """

    # Returns and weights on sector level for  benchmark
    w_b = np.array([sum(wb[int(i*n_stocks):int((i+1)*n_stocks)]) for i in range(n_sectors)])
    r_b = np.array([wb[int(i*n_stocks):int((i+1)*n_stocks)] @ ret[int(i*n_stocks):int((i+1)*n_stocks)] for i in range(n_sectors)])/w_b

    # Returns and weights on sector level for portfolio
    w_e = np.array([sum(we[int(i*n_stocks):int((i+1)*n_stocks)]) for i in range(n_sectors)])
    r_e = np.array([we[int(i*n_stocks):int((i+1)*n_stocks)] @ ret[int(i*n_stocks):int((i+1)*n_stocks)] for i in range(n_sectors)])/w_e

    # Total portfolio and benchmark return
    Re = np.dot(w_e, r_e)
    Rb = np.dot(w_b, r_b)

    # Relative Active Return
    active_return = ((1+Re) / (1+Rb)) -1

    # Naked allocation and selection effects
    sel_nkd = ((1+w_e*r_e) / (1+ w_e*r_b)) -1
    all_nkd = ((1 + (w_e-w_b)*r_b) /  (1+(w_e-w_b)*Rb)) -1


    # Q value
    q_top =  np.log(1+Re) - np.log(1+Rb) - sum(np.log((1+sel_nkd)*(1+all_nkd)))
    q_bottom = sum(np.log(1+sel_nkd)**2) + sum(np.log(1+all_nkd)**2)
    q_tot =  q_top/q_bottom
    
    # Perturbation terms
    gam_sel  = q_tot * np.log(1+sel_nkd)**2
    gam_all = q_tot * np.log(1+all_nkd)**2


    # Optimized selection and allocation effects
    sel_opt = (1+sel_nkd) * np.e**(gam_sel) - 1
    all_opt = (1+all_nkd) * np.e**(gam_all) - 1

    # Combined effect from allocation and selection
    combined_effect = np.prod(sel_opt+1) * np.prod(all_opt+1) 

    # Check ratio
    check_ratio = combined_effect / active_return

    return [all_opt, sel_opt, active_return, check_ratio, combined_effect]

In [316]:
svar = analyzer_time_t(ret_e, ret_b, exp_we, ben_we)
svar

[array([0.        , 0.01077339, 0.01319535]),
 array([-0.01965299,  0.        ,  0.        ]),
 np.float64(0.003984063745019917),
 np.float64(252.00000000000023),
 np.float64(1.00398406374502)]

In [322]:
svar[2] == svar[4]-1

np.True_

In [ ]:
# exp_we = np.array([0.4, 0.1, 0.2, 0.3])
# ben_we = np.array([0.25, 0.35, 0.3, 0.1])
# ret_v = np.array([0.025, -0.021, -0.013, 0.017])+1

# n_stocks = 2
# n_sectors = 2

In [169]:
exp_we = np.array([0.2, 0.5, 0.3])
ret_e = np.array([0.0, 0.04, -0.04])

ben_we = np.array([0.2, 0.2, 0.6])
ret_b = np.array([0.1, 0.04, -0.04])

n_stocks = 1
n_sectors = 3

In [337]:
wb = ben_we
ret_b = ret_b

we = exp_we
ret_e = ret_e

# def analyzer_time_t(ret_e:list ,ret_b:list,   we:list, wb:list):
#     """
#     one-liner

#     Args

#     Returns
#     """

# Returns and weights on sector level for  benchmark
w_b = np.array([sum(wb[int(i*n_stocks):int((i+1)*n_stocks)]) for i in range(n_sectors)])
r_b = np.array([wb[int(i*n_stocks):int((i+1)*n_stocks)] @ ret_b[int(i*n_stocks):int((i+1)*n_stocks)] for i in range(n_sectors)])/w_b

# Returns and weights on sector level for portfolio
w_e = np.array([sum(we[int(i*n_stocks):int((i+1)*n_stocks)]) for i in range(n_sectors)])
r_e = np.array([we[int(i*n_stocks):int((i+1)*n_stocks)] @ ret_e[int(i*n_stocks):int((i+1)*n_stocks)] for i in range(n_sectors)])/w_e

# Total portfolio and benchmark return
Re = np.dot(w_e, r_e)
Rb = np.dot(w_b, r_b)

# Relative Active Return
active_return = ((1+Re) / (1+Rb)) -1

# Naked allocation and selection effects
sel_nkd = ((1+w_e*r_e) / (1+ w_e*r_b)) -1
all_nkd = ((1 + (w_e-w_b)*r_b) /  (1+(w_e-w_b)*Rb)) -1


# Q value
q_top =  np.log(1+Re) - np.log(1+Rb) - sum(np.log((1+sel_nkd)*(1+all_nkd)))
q_bottom = sum(np.log(1+sel_nkd)**2) + sum(np.log(1+all_nkd)**2)
q_tot =  q_top/q_bottom

# Perturbation terms
gam_sel  = q_tot * np.log(1+sel_nkd)**2
gam_all = q_tot * np.log(1+all_nkd)**2


# Optimized selection and allocation effects
sel_opt = (1+sel_nkd) * np.e**(gam_sel) - 1
all_opt = (1+all_nkd) * np.e**(gam_all) - 1


In [336]:
Rb

np.float64(0.0040000000000000036)

In [ ]:
all_nkd*100

array([0.        , 1.07870555, 1.3215859 ])

In [ ]:
r_e

array([ 0.   ,  0.02 , -0.012])

In [ ]:
(1+Re) / (1+Rb)

np.float64(1.00398406374502)

In [ ]:
Re

np.float64(0.008000000000000007)

In [ ]:
Rb

np.float64(0.0040000000000000036)

In [ ]:
print(sel_nkd)

[[-0.00332226 -0.00662252 -0.00459418]
 [ 0.00199734  0.00398936  0.00276413]
 [ 0.00200803  0.00403226  0.00278465]]


In [ ]:
# svar = analyzer_time_t(ret_e, ret_b, exp_we,  ben_we)
# # print("Allocation:", svar[0])
# # print("Selection:", svar[1])
# # print("Active return:", svar[2])

In [ ]:
exp_R = np.dot(ret_e, exp_we)
ben_R = np.dot(ret_b, ben_we)
active_return = (1+exp_R)/(1+ben_R)
print("Experimental return: ",exp_R)
print("Bennchmark return: ",ben_R)
print("Active return: ",active_return-1)

Experimental return:  0.008
Bennchmark return:  0.0040000000000000036
Active return:  0.003984063745019917


In [ ]:
ben_R * 1.0137

np.float64(0.004054800000000003)

In [ ]:
act_ret = (1+exp_R)/(1+ben_R)
print("Active return from portfolio returns:", act_ret)

act_ret_from_effects = (np.prod(svar[1]) * np.prod(svar[0]))
print("active return from effects:", act_ret_from_effects)

Active return from portfolio returns: 1.00398406374502
active return from effects: -0.0


In [ ]:
1.01035**2*(ben_R+1)

np.float64(1.0174384589957501)

In [ ]:
np.e**(act_ret_from_effects-1)

np.float64(1.010405523609018)